# Generated by Django 4.2.4 on 2023-08-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('año', models.DateField(max_length=10)),
                ('documento', models.CharField(max_length=10)),
                ('tipo_de_documento', models.CharField(max_length=10)),
                ('numero_de_ficha', models.CharField(max_length=7)),
            ],
        ),
    ]
