# Generated by Django 4.2.4 on 2023-09-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Aprendiz', '0002_alter_aprendices_año_alter_aprendices_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendices',
            name='año',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='aprendices',
            name='documento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aprendices',
            name='numero_de_ficha',
            field=models.PositiveIntegerField(),
        ),
    ]
